### PR TITLE
Switch macOS SDK to 11.0 for Python 3.8 (for testing)

### PR DESCRIPTION
**Pull request by bkpoon**
This is a draft pull request to build Boost.Python 1.74 packages for testing builds and runtime environments.

This is to match the switch for Python 3.8 from
https://github.com/conda-forge/python-feedstock/commit/da95584347c061218cc2f2795522437e8ca26460

The related issue is https://github.com/conda-forge/cctbx-base-feedstock/issues/22

Basically, some Boost.Python conversions behave differently with `python-3.8.10_h0e5c897_0_cpython` vs `python-3.8.10_h3a889e0_1_cpython` for `osx-64` (the rest of the environment remains the same). Other versions of Python for `osx-64` are not affected. The `osx-arm64` builds for Python 3.8.10 do not show the issue. The other platforms, `linux-64` and `win-64`, are not affected. 

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bkpoon** [comment]
I'm not sure why the Azure Pipelines builds did not start, but I'm building it here. https://dev.azure.com/cctbx-release/feedstock-builds/_build?definitionId=3&_a=summary

And it looks like I have to update the download location.

**Comment by bkpoon** [comment]
Looks like my issue persists even after rebuilding with the new SDK. It's odd since Python 3.9.4 is also built with the latest macOS SDK and links to CoreFoundation, but does not exhibit my issue on `osx-64` with the `boost` 1.74 package for Python 3.9. I'll close this and do some more debugging.

**Comment by jakirkham** [comment]
Could you please file an issue with a simple reproducer? Would be good to get some clarity on what isn't working

**Comment by bkpoon** [comment]
Sure, I just made #117. Let me know if any more information is needed.

**Comment by jakirkham** [comment]
Thanks! 😄

**Pull request closed without merging**
