### PR TITLE
Add python 3.7

### PR DESCRIPTION
**Pull request by mcs07**
Do I need to bump the build number?

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by mcs07** [comment]
Also, does anyone know what the best procedure would be to add python 3.7 builds for v1.67 and maybe also v1.66?

**Comment by scopatz** [comment]
@mcs07 - yes, you do need to bump the build number.  And if you want to go back and do previous versions, you have to reduce the version number and bump the build number past its last build.

**Comment by mcs07** [comment]
I guess it's probably best to do this as part of the compiler migration, so I think I'll just wait for the automated python3.7/gcc7 rebuild PR from the autotick bot. Presumably that is waiting on boost-cpp and numpy to be migrated.

**Comment by jakirkham** [comment]
Thanks for working on this, @mcs07. PR ( https://github.com/conda-forge/boost-feedstock/pull/64 ) adds the new compilers and adds Python 3.7. It has just now been merged. So new packages should be published soon. Given that, going to go ahead and close this. Would appreciate your help testing the new packages and hearing any feedback you may have. Thanks 😄

**Pull request closed without merging**
