### PR TITLE
rerender for python v3.6

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by isuruf** [comment]
Needs the VC features for `py36`

**Comment by scopatz** [comment]
how do I set that? is there any documentation you can point me to?

**Comment by isuruf** [comment]
I updated this wiki page for py36, https://github.com/conda-forge/staged-recipes/wiki/VC-features

**Comment by ocefpaf** [comment]
Not necessarily, you can use py>=35 ;-)

**Comment by isuruf** [comment]
@ocefpaf, can you edit the wiki then?

**Comment by scopatz** [comment]
Better yet, this really should be in the docs on building on windows :)

**Comment by scopatz** [comment]
Thanks @isuruf @ocefpaf this is now building on all platforms

**Comment by jschueller** [comment]
there's no need to bump the release number as it does not change the current binaries, it just adds new builds

**Comment by scopatz** [comment]
I feel safer having a new build number since it will overwrite the old packages if it doesn't

**Pull request merged**
