### PR TITLE
patch for _Py_fopen -> fopen

### PR DESCRIPTION
**Pull request by mattip**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Adopt upstream boostorg/python#344. Should be enough to get the PyPy3.7 migration to pass.

### CODE REVIEW

**Comment by mattip** [comment]
@conda-forge-admin, please rerender

**Comment by mattip** [comment]
this replaces all the open migration PRs #96 #106 #107 #108 #109 which can be closed.

**Comment by isuruf** [comment]
They can't be replaced, unless you copy the `.ci_support/migrations/pypy*.yaml` files here.

**Comment by mattip** [comment]
ahh. So what happens to those PRs if this gets merged?

**Comment by isuruf** [comment]
They'll have to be rebased.

**Comment by isuruf** [comment]
@conda-forge-admin, rerender

**Comment by mattip** [comment]
Nope. boost is using [internal structures](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=266873&view=logs&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=10fc5aa2-324e-5982-4c88-6b31fcab16b3&l=1587)
```
$BUILD_PREFIX/x86_64-conda-linux-gnu/include/c++/9.3.0/bits/unique_ptr.h:53:28: note: declared here
   53 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
libs/python/src/wrapper.cpp: In member function 'boost::python::override boost::python::detail::wrapper_base::get_override(const char*, PyTypeObject*) const':
libs/python/src/wrapper.cpp:28:50: error: 'struct PyMethodObject' has no member named 'im_self'
   28 |                   && ((PyMethodObject*)m.get())->im_self == this->m_self
      |                                                  ^~~~~~~
      |    ^~~~~~~~~~~~~~
./boost/python/detail/is_auto_ptr.hpp:17:1: note: in expansion of macro 'BOOST_PYTHON_IS_XXX_DEF'
   17 | BOOST_PYTHON_IS_XXX_DEF(auto_ptr, std::auto_ptr, 1)
      | ^~~~~~~~~~~~~~~~~~~~~~~

```

**Comment by mattip** [comment]
Deeper into the rabbit hole: on latest HEAD that problem is gone. It was fixed in boostorg/python#291

**Pull request merged**
