### PR TITLE
Fix compatibility issue with Python 3.11

### PR DESCRIPTION
**Pull request by jcarpent**
Related to #155
Patch commit from boostorg/python#385

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jcarpent** [comment]
@jakirkham This PR follows #155 and is ready for review.

**Review by jakirkham — APPROVED** [review]
Thanks Justin! 🙏

**Comment by jakirkham** [comment]
@jcarpent, looks like the patch doesn't apply cleanly. Could you please take a look at rebasing it?

**Comment by jcarpent** [comment]
Yes, sure.

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Justin! 🙏

**Comment by jcarpent** [comment]
I'm not able to rerun `osx osx_arm64_numpy1.20python3.8.____cpython`, the failure being independent from the fix I think.
@jakirkham Could you rerun it?

**Comment by jakirkham** [comment]
The failure there is due to issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1823 ). It's unrelated to the fix.

Intend to rerun it. However Azure has only one option to restart while jobs are running, which restarts all jobs. Once all jobs complete there is another option to rerun only failing jobs. So am waiting for the rest of the jobs to complete so that we can rerun only that job (and not risk seeing this error pop up in a different job or eat up more resources we don't need). Should add the automerge bot will ping us when the merge fails (due to the failing job). So we will know when we can restart the failing job. Hope that context is helpful.

**Comment by jcarpent** [comment]
Sounds good to me. Thanks a lot for your reply.

**Comment by jakirkham** [comment]
Restarting the failed job

**Comment by jcarpent** [comment]
Perfect. Thanks a lot @jakirkham

**Comment by jakirkham** [comment]
Thanks you! 🙏

Please let us know how it goes 🙂

**Pull request merged**
