### PR TITLE
add numpy x.x as dependency to compile boost_numpy

### PR DESCRIPTION
**Pull request by dolfim**

### CODE REVIEW

**Comment by dolfim** [comment]
I guess I still need to improve the tests and re render the feedstock.

**Comment by jakirkham** [comment]
Yep, adding `numpy x.x` requires a [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ).

**Comment by jakirkham** [comment]
Make sure to bump the build number when you are done.

**Comment by dolfim** [comment]
Should we wait for #29? Otherwise I can already bump it.

**Comment by jakirkham** [comment]
Yeah let's wait. I'd like to straighten out the headers first before adding a new feature in. Sound good?

**Comment by dolfim** [comment]
Yes. The headers issue is actually quite blocking for me. Numpy is just a plus which would allow py3, but can wait.

**Comment by jschueller** [comment]
why is there a merge commit ? could you rebase ?

**Comment by dolfim** [comment]
I merged the changes from #29. No problem squashing, but what? everything?

**Comment by jschueller** [comment]
squashing would be good too to avoid a merge commit:
you could squash version bump (15d621e) into numpy dependency (2dfa9d7) so to drop the merge commit (5f0e8d1)

**Comment by jakirkham** [comment]
Not as worried about the merge commit personally. That being said, it should be easy to fix if you run `git rebase master boost-numpy` and force push the changes, that should pretty much just work. It doesn't look like there would even be a conflict.

However, I'm more concerned about this failure on AppVeyor. Do you have any insight into this, @isuruf?

**Comment by dolfim** [comment]
The force push removed the CI build links. As a reference, the broken AppVeyor is at: https://ci.appveyor.com/project/conda-forge/boost-feedstock/build/1.0.97

**Comment by dolfim** [comment]
I cancelled the builds since we first should look into the Win build.

As a reference the working builds are:
* Travis: https://travis-ci.org/conda-forge/boost-feedstock/builds/194467981
* CircleCI: https://circleci.com/gh/conda-forge/boost-feedstock/71

**Comment by isuruf** [comment]
Does boost_numpy support static builds?

See the failure,
```
[00:08:14] compile-c-c++ buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\numpy\ufunc.obj
[00:08:14] ufunc.cpp
[00:08:14] c:\bld\recipe_1485186582361\_b_env\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
[00:08:14] msvc.link.dll buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_numpy-vc90-mt-1_63.dll
[00:08:14] msvc.manifest.dll buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_numpy-vc90-mt-1_63.dll
[00:08:14] common.copy C:\bld\recipe_1485186582361\_b_env\Library\lib\boost_numpy-vc90-mt-1_63.lib
[00:08:14] The system cannot find the file specified.
[00:08:14] 
[00:08:14]     copy /b "buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_numpy-vc90-mt-1_63.lib" + this-file-does-not-exist-A698EE7806899E69 "C:\bld\recipe_1485186582361\_b_env\Library\lib\boost_numpy-vc90-mt-1_63.lib"
[00:08:14] 
[00:08:14] ...failed common.copy C:\bld\recipe_1485186582361\_b_env\Library\lib\boost_numpy-vc90-mt-1_63.lib...
[00:08:14] common.copy C:\bld\recipe_1485186582361\_b_env\Library\lib\boost_numpy-vc90-mt-1_63.dll
[00:08:14] buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_numpy-vc90-mt-1_63.dll
```
and compare that to boost_python.
```
[00:08:13] c:\bld\recipe_1485186582361\_b_env\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
[00:08:13] msvc.link.dll buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_python-vc90-mt-1_63.dll
[00:08:13]    Creating library buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_python-vc90-mt-1_63.lib and object buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_python-vc90-mt-1_63.exp
[00:08:13] msvc.manifest.dll buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_python-vc90-mt-1_63.dll
[00:08:13] common.copy C:\bld\recipe_1485186582361\_b_env\Library\lib\boost_python-vc90-mt-1_63.dll
[00:08:13] buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_python-vc90-mt-1_63.dll
[00:08:13]         1 file(s) copied.
[00:08:13] common.copy C:\bld\recipe_1485186582361\_b_env\Library\lib\boost_python-vc90-mt-1_63.lib
[00:08:13] buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_python-vc90-mt-1_63.lib
[00:08:13]         1 file(s) copied.
```

A line similar to `Creating library buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_python-vc90-mt-1_63.lib and object buildboost\boost\bin.v2\libs\python\build\msvc-9.0\release\threading-multi\boost_python-vc90-mt-1_63.exp` is missing in boost_numpy.

**Comment by jakirkham** [comment]
Good point. Honestly I think there is a fair question as to whether we should even provide static libraries for Boost.Python. This setting made more sense for the rest of the Boost stack, but am not convinced it makes sense for things like Python where interacting with the interpreter is probably easier when using the shared library.

**Comment by jakirkham** [comment]
Though it does seem the Unix builds did generate a static library for Boost.NumPy.

**Comment by jakirkham** [comment]
Do you mind raising an issue [upstream]( https://github.com/boostorg/python ), @dolfim? Seems they keep the code for Boost.NumPy in Boost.Python so that should be the right place to ask. Would recommend including links to the CI logs here, build scripts, and maybe this PR as well. Perhaps they have some ideas of went wrong with the static builds on Windows.

**Comment by dolfim** [comment]
Let's see if we get help

**Comment by jakirkham** [comment]
Thank you. 😄

**Comment by jakirkham** [comment]
Maybe we can just skip the static library for Boost.NumPy on Windows for now. What do you think?

**Comment by isuruf** [comment]
Looking at the logs again, it's the shared library that's failing, not the static one

**Comment by dolfim** [comment]
I found this comment in the original CMakeLists.txt of the project, maybe it helps...

https://github.com/ndarray/Boost.NumPy/blob/master/CMakeLists.txt#L71

> In some cases, you may need to explicitly specify that a dynamic Boost is used; if so use:
> add_definitions( -DBOOST_ALL_DYN_LINK )

**Comment by jakirkham** [comment]
The somewhat frequent download issues with SourceForge are pretty annoying. Is there a more reliable place we can get the source from?

**Comment by jakirkham** [comment]
Could you please try a patch based on PR ( https://github.com/boostorg/python/pull/110 ), @dolfim?

Tip: Can add `.patch` or `.diff` on the end of the PR URL and that will take you to a file that gives you a patch or diff you can use (with some tweaks).

**Comment by jakirkham** [comment]
Thanks @dolfim. FWICT this is working. Could you give this one last look @isuruf?

**Comment by jakirkham** [comment]
Good point. That should be easy to add. Just do another re-render.

**Comment by dolfim** [comment]
Now it is re-rendered, and I also bumped the build version.

**Comment by jakirkham** [comment]
Thanks @dolfim for the contribution and @isuruf for reviewing.

**Pull request merged**
