### PR TITLE
Update ICU pin

### PR DESCRIPTION
**Pull request by ocefpaf**
cc @mingwandroid

Needs https://github.com/conda-forge/boost-cpp-feedstock/pull/9 first.

### CODE REVIEW

**Comment by ocefpaf** [comment]
`boost` does not seem to be linking to `icu` at all. I get this when building locally:

```shell
+ conda inspect linkages -p /opt/conda/conda-bld/recipe_1485974017094/_t_env boost
boost
-----

system:
    libc.so.6 (/lib64/libc.so.6)
    libdl.so.2 (/lib64/libdl.so.2)
    libgcc_s.so.1 (/lib64/libgcc_s.so.1)
    libm.so.6 (/lib64/libm.so.6)
    libpthread.so.0 (/lib64/libpthread.so.0)
    librt.so.1 (/lib64/librt.so.1)
    libstdc++.so.6 (/usr/lib64/libstdc++.so.6)
    libutil.so.1 (/lib64/libutil.so.1)
    linux-vdso.so.1 ()

not found:


TEST END: boost-1.63.0-py35_5
```

@isuruf should we remove it from the dependencies? (The new `boost-cpp` does link to `icu`.)

**Comment by isuruf** [comment]
Yes, icu is needed only for `boost_regex`. You can remove it from here.

**Comment by isuruf** [comment]
You can remove the pinning of bzip2 and zlib as well.

**Comment by ocefpaf** [comment]
> You can remove the pinning of bzip2 and zlib as well.

You mean remove the dependency, right? Not only the pinning.

**Comment by isuruf** [comment]
> You mean remove the dependency, right? 

Yes.

**Comment by ocefpaf** [comment]
>> You mean remove the dependency, right? 

> Yes. 

Thanks @isuruf will do. Still waiting on `boost-cpp` though.

**Comment by jakirkham** [comment]
Thanks for the cleanup.

**Pull request merged**
