### PR TITLE
Build both static and dynamic libraries for components

### LINKED ISSUE #4: Need to package both static and dynamic libraries for components
Currently only dynamic libraries are being built. This causes problems in projects with build dependencies on boost requiring the static libraries:

https://circleci.com/gh/conda-forge/staged-recipes/3253

```
CMake Error at /opt/conda/envs/_build/share/cmake-3.5/Modules/FindBoost.cmake:1647 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.60.0

  Boost include path: /opt/conda/envs/_build/include

  Could not find the following static Boost libraries:

          boost_filesystem
          boost_thread
          boost_unit_test_framework
          boost_date_time
          boost_atomic
```

If no one beats me to it, here is one example of building the complete Boost library stack:

https://github.com/cloudera/native-toolchain/blob/master/source/boost/build.sh

### PR DESCRIPTION
**Pull request by wesm**
Closes #4

### CODE REVIEW

**Comment by ocefpaf** [comment]
Thanks @wesm!

**Comment by jakirkham** [comment]
Weird. That didn't build on Windows.

**Comment by jakirkham** [comment]
There was a failure on `master` with AppVeyor, but it appears to have simply failed to download Obvious-CI on the Python 2.7 builds, but passed the rest. This appears to be a fluke and not a real failure so I have restarted the build on the merged commit. Hopefully, we will get the two Windows Python 2.7 builds soon.

**Comment by jakirkham** [comment]
The Python 2.7 builds on AppVeyor have started and passed the Obvious-CI step. Hopefully, it is smooth sailing ⛵ from here. We should know in about 10mins how things have gone.

**Comment by jakirkham** [comment]
There are now Windows Python 2.7 packages. So, we now should have this support. Though I would like to have us work on our tests here a bit more.

**Comment by jakirkham** [comment]
To be more specific, it looks like the static libraries on Windows are named `libboost_*` instead of `boost_*`. So, we need to be checking for this.

**Comment by jakirkham** [comment]
Added an issue related to these tests here ( https://github.com/conda-forge/boost-feedstock/issues/7 ).

**Pull request merged**
