### PR TITLE
Update to 1.64

### PR DESCRIPTION
**Pull request by jschueller**

### CODE REVIEW

**Comment by isuruf** [comment]
Hmm, CircleCI is not building the PR

**Comment by jschueller** [comment]
It's weird, dlls are not installed

**Comment by bluescarni** [comment]
I've run into similar issues while trying to compile in MinGW. Other people have reported the problem as well:

https://www.reddit.com/r/cpp/comments/66cfhv/boost_v1640/dgi1jww/

**Comment by jschueller** [comment]
I dont see anything in the log though.

**Comment by bluescarni** [comment]
Maybe relevant?

https://github.com/boostorg/build/issues/194

**Comment by jschueller** [comment]
Totally the same issue, thanks for the pointer.

**Comment by jschueller** [comment]
Could someone from @conda-forge/core investigate why circleci is not starting the pr ?

**Comment by jakirkham** [comment]
This happened to someone else and I think their CircleCI settings got messed up somehow. Could you please check your CircleCI settings are all in order?

**Comment by jschueller** [comment]
see #37

**Comment by jschueller** [comment]
I unregistered circleci and deleted my fork, that made it work, thanks.

**Comment by jakirkham** [comment]
Glad you got it to work, @jschueller.

**Pull request closed without merging**
