### PR TITLE
Added  -std=c++14 flag

### PR DESCRIPTION
**Pull request by xmnlab**

### CODE REVIEW

**Comment by scopatz** [comment]
I think we need to wait for the new compilers

**Comment by xmnlab** [comment]
@scopatz 

is there some idea about when the new compilers will be available?

**Comment by scopatz** [comment]
Folks are working on it now, so "soon" hopefully

**Comment by jschueller** [comment]
when using the new compiler syntax, it pull gcc 7.2 which default to using c++14, so this should be useless now, reopen if needed

**Comment by xmnlab** [comment]
Thanks for the update!

**Pull request closed without merging**
